### ISSUE TITLE
Data Download and test/train Split

### ISSUE THREAD

**Issue by avl02** [songyoungoh/team_bassconnections#13]
- [x] Create a link accessible to everyone from either a google drive or the main EuroSat page for the data

- [x] Create a new .py file for downloading and splitting data into test/train using specified seed for reproducible results

**Comment by muazkashif** [comment]
For the second task I added a data_download method to data.py instead of a new py file. Do you guys think that's the better approach?

**Comment by songyoungoh** [comment]
Yup, I like that method. Much better!
