### ISSUE TITLE
More detail needed in the instructions

### ISSUE THREAD

**Issue by kylebradbury** [songyoungoh/team_bassconnections#2]
We need more detail in this section: 
https://github.com/songyoungoh/team_bassconnections/blob/7a98733c3cc64e5432e4b321e23540ef23e67034/README.md?plain=1#L20-L23

At present, these instructions are insufficient to successfully run the code.

In particular, we need:
1. Where do we save the downloaded dataset? Do we need to unzip anything? Where does it need to be placed in the folder directory? What should the folder be named?
2. Run which notebook? There are multiple. What does each do and why and when should it be run?

**Comment by songyoungoh** [comment]
I have added more details in the instructions. Please let us know if we can improve it more!

**Comment by kylebradbury** [comment]
It looks like it's been improved, but currently references main.ipynb - should be updated with the latest changes

**Comment by mgpruch** [comment]
ReadMe no longer mentions main.ipynb, now instead references the files a user needs to run
