### ISSUE TITLE
Create a makefile

### ISSUE THREAD

**Issue by kylebradbury** [songyoungoh/team_bassconnections#6]
Would be good to have options for:

- prepare (download, unzip, and split into train/test)
- train (fit the model)
- evaluate (run the evaluation script and get metrics)
- "run all" to do all of the above

**Comment by DaryLu0v0** [comment]
Add a run-all option. for the separate function, I am still working on it

**Comment by DaryLu0v0** [comment]
All options(prepare, train, eval) are added
