### ISSUE TITLE
Reproducible Data

### ISSUE THREAD

**Issue by mgpruch** [songyoungoh/team_bassconnections#7]
We need to modify the link to the dataset test/training splits so that it is accessible by anyone using this Git. We also need more clear explanation of how to use the data, so that our code and results are fully reproducible.

**Comment by songyoungoh** [comment]
Yeah, the current link in README file requires additional access. So, Muaz's code for downloading data would be pulled from his branch to the main branch in a minute.

**Comment by songyoungoh** [comment]
I've also updated README file to explain how our files can be used with more details.

**Comment by songyoungoh** [comment]
I've added comments what the other folders (such as results and reports) contain in our repository.
